### ISSUE TITLE
Missing module configuration parameter

### ISSUE THREAD

**Issue by stratosgear** [cniska/yii-auth#56]
In yii-auth / views / layouts / main.php you are refering to appLayout like:

$this->beginContent($this->module->appLayout)

but the appLayout field in AuthModule.php is missing.

If you add it, and provide a valid appLayout configuration parameter in your config file, everything works fine.

**Comment by cniska** [comment]
This should already be fixed.

**Comment by kkhugs** [comment]
This is actually still broken: https://github.com/Crisu83/yii-auth/blob/master/views/layouts/main.php on line 3, this should be `$this->module->layout` rather than `$this->module->appLayout`. This seems to be a carryover for a setting that was in Rights, as far as I can tell. Changing this as I described fixes inconsistencies with the layout (currently it uses the default theme instead of bootstrap).
